### ISSUE TITLE
Research Github API's and code analyzer tools 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#10]
For Tuesday October 2nd, look into the Github API and document some of the useful things we can use. Also,  research code analysis tools available in the following languages 

Java- Zed
Python - Pedro, 
JavaScript - Prin 
 TBD - Prakhar

**Comment by pjmc-oliveira** [comment]
Me and Prin did some basic testing of the API. Should be possible to get the required data from it.
