### ISSUE TITLE
UI : ADD TauChart  Chart Controls 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#101]
Currently, the x and y axis are data can not be altered. The task is to add buttons and functionality that would allow the x/y axis to be changed and the chart to be re-rendered.

**Comment by ahmadzed** [comment]
Desired controls:  

X-Axis parameter  
Y-Axis parameter(s?)  
Grouping parameter?  (Default: extension.  Maybe unnecessary to display this in any other way?)  

Data filters:  
* By extension  
* By commit date range

**Comment by ahmadzed** [comment]
The following controls have been implemented:
X-Axis parameter  
Y-Axis parameter (only one currently)  
Extension filter (through taucharts plugin)  
Date range filter (through taucharts plugin)  

Scrapped grouping parameter, the data must be grouped by extension to be parsed correctly.

May look into having multiple parameters on the y axis as a future improvement.  Issue closed for now.
