### ISSUE TITLE
Wiki: Clarify python3 naming in Quick Start

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#113]
My understanding of Task : 

Update Python section of Quick Start to clarify the difference of calling python3 or python for windows versus macOSX.  Similarly, when to use pip3 versus pip. 

@ahmadzed ,  Can you please confirm my understanding of this task.

**Comment by ahmadzed** [comment]
Your understanding is correct!  Wiki has been updated.
