### ISSUE TITLE
Go the Underground and Ask How much Gorilla/Thesis Poster Printing Costs 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#12]
Go the Underground and Ask How much Gorilla/Thesis Poster Printing Costs

**Comment by PrakharJalan** [comment]
It's going to be $5 per square foot for matte finish, and $7 per square foot for glossy. 
We just need to email the poster in PDF format, along with its dimensions (in inches) to 'underground@msu.mcmaster.ca' and they should have it done within 2-3 business days.

**Comment by selvatp** [comment]
How many Square foot is a poster? :S  3 * 3 enough ? or 3 * 4 ?

**Comment by PrakharJalan** [comment]
> How many Square foot is a poster? :S 3 * 3 enough ? or 3 * 4 ?

I would say a 36x48 (inches) poster would be good as it's the average size. In feet, that's equivalent to 3 * 4.
