### ISSUE TITLE
Requirements Specifications Document :  Project Drivers & Project Constraints # 6

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#20]
Complete the following sections of the Requirements Specifications Template : 

\section{Project Drivers}
\subsection{The Purpose of the Project}
\subsection{The Client the Customer, and Other Stakeholders}
\subsection{Users of the Product}

\section{Project Constraints}
\subsection{Relevant Facts and Assumptions}

**Comment by PrakharJalan** [comment]
Completed Project Drivers and (Facts and Assumptions). Subject to change based on applying Dr. Smith's suggestions and feedback.
