### ISSUE TITLE
Requirements Specifications Document : Functional Requirements Review

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#32]
Review the Functional Requirements and ensure: 

The qualities of a good requirements specification (which you should inspect your SRS for) are: clear, unambiguous, understandable; consistent; complete (internal and external); incremental; validatable; abstract and traceable.  Some information on these specification qualities can be found starting on slide 18 at :

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/Lectures/L05_ProgramFamilies/ProgramFamilies.pdf

**Comment by selvatp** [comment]
The SRS updates are complete. Please kindly complete the review as soon as possible such that we can complete any necessary updates and pass it to Dr.Smith

**Comment by selvatp** [comment]
Changes were put in based on Pedro's feedback

**Comment by smiths** [comment]
The SRS looks good.  After a quick scan I have a few comments:

- On page 4 you could mention me as a client.  The current plan is to use your software to measure the "quality" of scientific computing software.
- You use underlining for some of your headings.  Your report would look better without underlining.
- FR1 mentions selected metrics, but I don't believe you have a list of the available metrics anywhere.
- FR3 mentions a help section for a command line interface.  I don't know what that means.  Maybe you mean that your command line tool will have a man page?
- Nice to see a survey mentioned in your non-functional requirements.  You will need to get an implementation done soon to have time to do a proper survey.

**Comment by PrakharJalan** [comment]
Made all the recommended changes.
