### ISSUE TITLE
Review of Requirements Specifications Document

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#34]
Task to review requirements of specifications document. To be done by all members non-involved in its authoring & Dr.Smith

**Comment by selvatp** [comment]
@smiths  
It is my understanding that the SRS is now ready to be reviewed. There isn't a timeline for its completion. Whenever is most convenient for yourself. 

Cheers

**Comment by PrakharJalan** [comment]
SRS already reviewed by Dr. Smith
