### ISSUE TITLE
JS Code Module:  Lines of Comments

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#40]
Task is to add function that finds/calculates "Number of Lines of Comments".

Completion Criteria:
1. Commit of Function
2. JSDOC Comments 
3. Comment in task about what input/output you tested this function with .

**Comment by ahmadzed** [comment]
Lines of Comments function completed for Javascript.

TODO: calculate lines of comments for python, also reconsider quantifying as lines vs bytes etc?

**Comment by selvatp** [comment]
Scope of this task changed. Lines of comments function completed for Javascript as per @ahmadzed 's commit. Closing task and opening new one for Python
