### ISSUE TITLE
JS Code Module: Number of Dependencies for JS files 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#46]
Task is to add function that finds/calculates "Number of Dependencies of the Repo".

These dependencies are defined in HubListener’s manifest files, such as src/package-lock.json and src/package.json.

Completion Criteria:

Commit of Function
JSDOC Comments
Comment in task about what input/output you tested this function with

**Comment by pjmc-oliveira** [comment]
Not supported by GitHub API yet. Would have to read the cloned repo. Currently too broad and language dependent, needs further discussion.

**Comment by selvatp** [comment]
Updated scope of the Task to find the dependencies for Javascript files aka package.json

**Comment by ahmadzed** [comment]
Currently we do count average javascript dependencies per module (simple require/import statements)  
Anything else seems to be out of scope - analyzing package manager files (ie package.json) to generate metrics for js source code does not fit hublistener's current architecture.
