### ISSUE TITLE
Review Parnas's Rational Design: How and Why to Fake It

### ISSUE THREAD

**Issue by smiths** [pjmc-oliveira/HubListener#47]
In a previous meeting I mentioned this paper by Parnas.  This it the justification for the "waterfall" documentation style we are faking.  This isn't a priority to review, but I told you that I would send you a link:

https://gitlab.cas.mcmaster.ca/smiths/cas741/blob/master/ReferenceMaterial/ParnasAndClements1986.pdf

Once you have had a quick look at this paper, feel free to close this issue.  If you have any questions, let me know.

**Comment by PrakharJalan** [comment]
Reviewed the paper by Parnas.
