### ISSUE TITLE
Version 1 :  JSDocs

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#55]
This task is to get JS Docs set up such that we get the appropriate reports. This will also be helpful for the onboarding. 

http://usejsdoc.org/

**Comment by pjmc-oliveira** [comment]
Done, see:
b0d97d4a6a1672b3917fdf3247317838a5677328
de2af4bcdc3617c119fa2504776ea5fa5ddb9bb9
4069b6481fa11cc07c1a9ee1991b4b159db052a2
78448f94893d11b3abdf93dd7945acc49cd807c4
d96269a8174608d6b1e022c1be8554f007ffb5d0
