### ISSUE TITLE
Version 1: Command Line Interface  - Argument Parsing 

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#56]
The goal of this task is to create the command line interface for the HubListener tool such that the application accepts arguments such as --help, URL, no-clone, out, append and any other short forms that need to be added.

**Comment by pjmc-oliveira** [comment]
Done see commits:
68e73a8a344c547489e97ed057692a00b3703f4c
6fc908aa428c79953e5734b7ba3e11bb8ba8b4e7
