### ISSUE TITLE
Discuss and integrate 'dev' script into workflow

### ISSUE THREAD

**Issue by pjmc-oliveira** [pjmc-oliveira/HubListener#61]
The [dev.js](https://github.com/pjmc-oliveira/HubListener/blob/master/src/dev.js) has been created, including a 'npm run dev' script to automatically generate JSDoc files on saves. Discuss integrating into contributors guide, and developer workflow.

**Comment by pjmc-oliveira** [comment]
Potentially add additional functionally to script

**Comment by selvatp** [comment]
Created task #64  as per our discussion to include into contributors guide and
