### ISSUE TITLE
House Keeping : Update Main readme.md

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#63]
The current Read.me does not provide information about the project. It needs to be more in depth. It is okay if it seems like we are repeating ourselves because this is the first thing people will see! 

It should follow DRASIL(https://github.com/JacquesCarette/Drasil) Example Dr.Smith gave us : 

*Headers* - *Person assigned*
What is HubListener? - @PrakharJalan 
Quick Start - @ahmadzed 
Command Line Options - @pjmc-oliveira 
Finding/Building the JSDocs - @pjmc-oliveira 
Summary of Folder Structure and File Contents - @selvatp 

To be done later.... Running Examples && Running Automated Testing

**Comment by selvatp** [comment]
Updated File Directory information on readme.md. Please review and let me know

**Comment by pjmc-oliveira** [comment]
Added JSDoc and Quick Start link

**Comment by selvatp** [comment]
All components completed. Marking as closed
