### ISSUE TITLE
Wiki :  Add JS Docs Usage

### ISSUE THREAD

**Issue by selvatp** [pjmc-oliveira/HubListener#64]
This task is two parts:

1. Add to the Contributors Guide steps that explain how to run the JS DOCs aka “npm run dev”
*Be descriptive *

2. Add a link to the Quick Start Guide that links the above part 1.

**Comment by ahmadzed** [comment]
Added to the [Contributor's Guide](https://github.com/pjmc-oliveira/HubListener/wiki/Contributor%27s-Guide)
