### ISSUE TITLE
Delete temporary clone after use

### ISSUE THREAD

**Issue by pjmc-oliveira** [pjmc-oliveira/HubListener#71]
Currently the app clones the git repo into a temporary directory to be cleared by the system. Script should actively delete the cloned repo on exit.

**Comment by selvatp** [comment]
Suggestion made to clone the repo to its own folder in the src folder. For example, a folder called HubListener would be created and the clone would happen in said folder. All the "results" would also manifest in there. 

Re-running the same URL would just overwrite the existing folder.

**Comment by selvatp** [comment]
Suggestion was pushed to master branch. 
Now creates folders for repos cloned . Re-Pull's if already exits.
