### ISSUE TITLE
Finalize set of metrics, add labels and descriptions for each

### ISSUE THREAD

**Issue by ahmadzed** [pjmc-oliveira/HubListener#79]
Need to fully define all metrics returned for each of the following groups:  

- Generic static analysis
- Javascript static analysis
- Python static analysis
- GitHub API metrics

**Comment by selvatp** [comment]
Generic static analysis -NONE 
Javascript static analysis - ESPREMA 
Python static analysis - RADON 
GitHub API metrics - In progress .

New issue tb=o be created
