### ISSUE TITLE
Change /analyse to be able to run on 'not-yet analysed' repositories

### ISSUE THREAD

**Issue by pjmc-oliveira** [pjmc-oliveira/HubListener#93]
Currently /analyse pulls already analysed commits from the data and combines with new commits (which it analyses) and returns it. However the way it's currently implement assumes there's always an existing commit present in the database. Change it from "analyse everything after the last commit in the database" to "analyse everything from the last commit in the database or everything if there's no previous commit in the database"

**Comment by selvatp** [comment]
Completed by @pjmc-oliveira  94a8cfb48901f6576135c47a4aa1a5f29c2acc33
